server:
  port: 8010

spring:
  application:
    name: service-product
  cloud:
    nacos:
      #      discovery:
      #        service: ${spring.application.name}
      #        server-addr: ${spring.cloud.nacos.server-addr}
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false